### ISSUE TITLE
SPDX License Knowledgebase does not work with proxy settings

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#352]
### Summary of the Bug

When running antenna with the SPDX license knowledge base, the maven log reports an error that an io error happened while configuring the knowledge base and later that the knowledge base is using a local file because of missing access to the online data. In the cli the configuration of the knowlegde base even breaks with an uncaught exception.

### Steps to reproduce
- Run the standard configuration in a proxy protected environment
- Observe the error and warnings in the maven log output
- Observe the break of the cli running

### Acceptance Criteria
- [ ] Proxy settings are also used for the spdx license knowledge base
- [ ] Proxy settings are used, if a proxy is defined in the configuration

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by bs-ondem** [comment]
@blaumeiser-at-bosch  Just to be sure, are you talking about the following Errors/Warnings:
```
...
[ERROR] I/O error opening Json TOC URL, using local TOC file
...
[INFO] Run org.eclipse.sw360.antenna.workflow.processors.LicenseKnowledgeBaseResolver
...
[DEBUG] open(https://spdx.org/licenses/MIT.jsonld)
[DEBUG] Not mapped: https://spdx.org/licenses/MIT.jsonld
[DEBUG] [1] GET https://spdx.org/licenses/MIT.jsonld
[WARNING] Unable to open SPDX listed license model.  Using local file copy for SPDX listed licenses
```

**Comment by blaumeiser-at-bosch** [comment]
I can remember the last of the warnings. I have not checked it with debug, since it looked compared to a non-proxy situation a lot like: sorry, can't access the external site.

**Comment by bs-ondem** [comment]
The `I/O error` only occurs if you are in the BCN. The reason for the log output is an `UnknownHostException`, which is caught here https://github.com/spdx/tools/blob/master/src/org/spdx/rdfparser/license/ListedLicenses.java#L349-L352

**Comment by bs-ondem** [comment]
The method [`ListedLicenses::loadListedLicenseIds`](https://github.com/spdx/tools/blob/master/src/org/spdx/rdfparser/license/ListedLicenses.java#L332-L393) tries just to load the listed license IDs from the SPDX website https://spdx.org/licenses/licenses.json without any proxy nor proxy authentication information. If an exception is thrown, it will be caught and an error log output will be printed. 
Afterwards it tries to load the listed license IDs from the class loader, i.e. the spdx-tools binary contains all the licenses IDs and the `licenses.json` file. 


The question that arises for me is @blaumeiser-at-bosch:
Does it matter to Antenna at all whether the License IDs are loaded from the website or from the JAR file? 
  - If yes, we have to make changes in `spdx-tools` that the method [`ListedLicenses::loadListedLicenseIds`](https://github.com/spdx/tools/blob/master/src/org/spdx/rdfparser/license/ListedLicenses.java#L332-L393)  goes through an proxy if needed. 
  - If no, no changes are needed because the license IDs can also be loaded from the JAR file. 

And I was not able to reproduce the break with the CLI. Can you provide some more information about your CLI settings?

**Comment by blaumeiser-at-bosch** [comment]
Ok, we should somehow document this, but I do not think that the problem is worth a fix for now. SPDX tools are though a topic for itself, so perhaps we may solve this in the future.

**Comment by kallesoranko** [comment]
There is still a problem related to this, since it is waiting until time-out for every component if Antenna is behind the proxy. I just had a project with 125 components and the Antenna stage in a pipeline failed because of timing out after five hours. In case that this is not worth fixing, would it be possible to disable the requests to https://spdx.org/licenses/licenses.json completely?

**Comment by bs-ondem** [comment]
Hi @kallesoranko,
the problem is that the request is done by [spdx-tools -> ListedLicenses::loadListedLicenseIds ](https://github.com/spdx/tools/blob/master/src/org/spdx/rdfparser/license/ListedLicenses.java#L344-L345) and if the request fails, it will load (in the spdx-tools jar file) license information locally. 

All of this is done by SPDX and therefor we have no influence on it, which means that spdx-tools should provide the functionality to work behind the proxy.

**Comment by blaumeiser-at-bosch** [comment]
Found something: In ListedLicenses there is the following property:
`
    boolean onlyUseLocalLicenses;

    private ListedLicenses() {
        this.onlyUseLocalLicenses = Boolean.parseBoolean(System.getProperty("SPDXParser.OnlyUseLocalLicenses", this.licenseProperties.getProperty("OnlyUseLocalLicenses", "false")));
        this.loadListedLicenseIDs();
    }
`

The flag is used to prevent downloading of stuff prior to using local stuff. This should solve your problem @kallesoranko .

If so, please give feedback, so we can update the documentation. Or perhaps you have an easy idea on how to set this programmatically in behind proxy use cases?

**Comment by kallesoranko** [comment]
Thanks @blaumeiser-at-bosch, this is exactly what I need. I will test this and get back to you.
