### ISSUE TITLE
Compliance Tool: Updating the same release twice with different licenses does not update the licenses

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#588]
### Summary of the Bug
When running the compliance tool updater twice with the same release set to `OSM_APPROVED` but changing the declared, observed or overwritten license does not update it the second time. 

### Steps to reproduce
- Run the same release with different licenses twice with the `OSM_APPROVED` flag in the updater

### Acceptance Criteria
- [ ] understand where this behaviour comes from
- [ ] Release gets updated with all data each time the updater run. 
- [ ] New run with `OSM_APPROVED` takes precedence

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by neubs-bsi** [comment]
Exact desired behaviour needs to be discussed:
Do we want the release to be updateable after first approval or not? Are there conditions?

**Comment by neubs-bsi** [comment]
Depends on https://github.com/bosch-io/osm-antenna/issues/942

**Comment by neubs-bsi** [comment]
Currently, it is true, that once a release is set to approved with the compliance tool, no  more changes can be done via the compliance tool. currently this is because of https://github.com/eclipse/antenna/issues/587. until it is fixed, this issue can't continue

**Comment by KorSin** [comment]
During working on #619, I experienced that some fields, including the license, are not updated. The reason seems to be [here](https://github.com/eclipse/antenna/blob/a66aa2e60b17c51d63b97a87cea2e310ace1eb9f/modules/sw360/sw360-workflow/src/main/java/org/eclipse/sw360/antenna/sw360/SW360MetaDataUpdater.java#L134-L135). After the updater has read a release from a csv file, a corresponding release is searched for in SW360. If found, it is merged together with the local one in which case the SW360 release takes the precedence. The actual update is performed with the merged one, making changes in the local release redundant. Maybe changing the priority during the merge just solves the problem.
